# 机器人配置
appid: "10000000"
secret: "2rgVKA0qkkxxx1exampledVNF7zsleX"

# 短链接服务配置(实现详见utils.py)
# 域名需要自己在机器人后台配置并验证
short_url: "https://example.com/code"
payload_field: "url"  # payload参数的字段名

# 内容上传服务，用于QQ发送失败后发送链接
content_upload: "https://example.com/upload"  # 上传内容的接口

# kimiAPI
kimi:
  url: "https://api.moonshot.cn/v1"
  key: "sk-7wU8LHxRKxxxxxxxxxxxxxxxxxxxxBZ1cKmwK"
  model: "moonshot-v1-8k"

# 硅基流动接口
SiliconCloud:
  url: "https://api.siliconflow.cn/v1"
  key: "sk-dtthnofxxxxxxxxxxxxxxxxxxxxxxxbcczckrwnoj"
  model: "deepseek-ai/DeepSeek-V3"
