# 机器人配置
appid: "10000000"
secret: "2rgVKA0qkkxxx1exampledVNF7zsleX"

# kimiAPI
kimi:
  url: "https://api.moonshot.cn/v1"
  key: "sk-7wU8LHxRKxxxxxxxxxxxxxxxxxxxxBZ1cKmwK"
  model: "moonshot-v1-8k"

# 硅基流动接口
SiliconCloud:
  url: "https://api.siliconflow.cn/v1"
  key: "sk-dtthnofxxxxxxxxxxxxxxxxxxxxxxxbcczckrwnoj"
  model: "deepseek-ai/DeepSeek-V3"
